---
title: "KNN"
author: "Tim Modul"
date: "10/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#load library (install dahulu jika belum diinstall)

library(class)# untuk membuat model KNN
library(caret)# membangun confusion matriks, melihat akurasi model


# load data
ipeh<- read.csv("../dataset/data_Ipeh.csv", header=T)
View(ipeh)

```

```{r}
#ngulik ngulik variabel
str(ipeh)

# ubah tipe variabel admit menjadi tipe faktor
ipeh$admit=as.factor(ipeh$admit)

#normalisasi dengna feature scalink
normalisasi<-function(r){
  return((r-min(r))/(max(r)-min(r)))
}

#normalisasi semua atribut kecuali target class
for(i in colnames(ipeh[-1])){
    ipeh[ ,i]=normalisasi(ipeh[ ,i])
}

str(ipeh)

```

```{r}
# memecah data menjadi data training(80% dari data awal) dan data test (20% dari data awal)
set.seed(1234)
sampel<-sample(2,nrow(ipeh),replace = T, prob = c(0.8,0.2))

trainingdat<-ipeh[sampel==1, ]
testingdat<-ipeh[sampel==2, ]

#model
prediksi<-knn(train = trainingdat, test = testingdat, cl=trainingdat$admit ,k=20)
#cl merupakan faktor dari klasifikasi yang benar dari training set

#melihat akurasi dari model
confusionMatrix(table(prediksi, testingdat$admit))


#melihat k yang optimal, biasanya k yang optimal adalah di sekitar akar dari banyak observasi (k=20)
optimal=0
for(i in 1:100){
  prediksiknn<-knn(train=trainingdat, test = testingdat, cl=trainingdat[,1], k=i)
  optimal[i]<-100*sum(testingdat$admit==prediksiknn)/nrow(testingdat)
  k=i
  cat(k,"=",optimal[i],'\n')
}
```



